name: Build and deploy Vite app to Azure Web App - edu (Staging)

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    outputs:
      site-path: ${{ steps.zip-site.outputs.site-path }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies and build
        env:
          VITE_API_URL: ${{ secrets.STAGING_VITE_API_URL }}
          VITE_APP_API_URL: ${{ secrets.STAGING_VITE_APP_API_URL }}
          VITE_APP_NAME: ${{ secrets.STAGING_VITE_APP_NAME }}
          VITE_APP_VERSION: ${{ secrets.STAGING_VITE_APP_VERSION }}
          GENERATE_SOURCEMAP: ${{ secrets.STAGING_GENERATE_SOURCEMAP }}
          VITE_APP_CRM_API_KEY: ${{ secrets.STAGING_VITE_APP_CRM_API_KEY }}
          VITE_APP_STREAM_API_KEY: ${{ secrets.STAGING_VITE_APP_STREAM_API_KEY }}
        run: |
          npm ci
          npm run build
          zip -r site.zip dist

      - name: Save zip path for next job
        id: zip-site
        run: echo "site-path=$(pwd)/site.zip" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read  # Required for actions/checkout

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7418B2132FDB474CA49D0B809C085439 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F6B61FEDF7C24ADFB93495C2F3F8D674 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1E708C7368B54B6EA3BCD1696261A5F9 }}

      - name: Deploy to Azure Web App (Staging)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'edu'
          slot-name: 'staging'
          package: ${{ needs.build.outputs.site-path }}
